#page title
page_title                                : Karate Shorin Ryu                                            # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6448687503                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store/apps/details?id=app.shorinryu.karate           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Karate Shorin Ryu                         # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Curated content to help you improve in your daily karate practice.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Cristopher Oyarzún                                
your_link                                 :                     
your_city                                 : Santiago, Chile                                
email_address                             : c.oyarzun@gmail.com
facebook_username                         :                                           
instagram_username                        : coyarzun89
twitter_username                          : 
github_username                           : coyarzun89
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : What is Shorin ryu?
    description                           : Shōrin-ryū is one of the major modern Okinawan martial arts and is one of the oldest styles of karate. It was named by Choshin Chibana in 1933, but the system itself is much older.
    fontawesome_icon_name                 : torii-gate

  - title                                 : Who was Chōshin Chibana?
    description                           : Chōshin Chibana was a top student of the great master of shuri-te, Ankō Itosu. Ankō Itosu was the top student of Matsumura Sōkon, who was a renowned warrior in his time.
    fontawesome_icon_name                 : fist-raised

  - title                                 : What are the main branches of Shorin ryu?
    description                           : There are currently four major branches of Shōrin-ryū Karate practiced in the world today, Kobayashi-Ryu, Shobayashi-Ryu, Matsubyashi Ryu and Matsumura Seito.
    fontawesome_icon_name                 : code-branch

  - title                                 : What are the active schools of Shorin ryu?
    description                           : 
        "Some of the active schools are:
        <br/>
        Shōrin-ryū Shidōkan
        <br/>
        Shōrin-ryū Shōrinkan
        <br/>
        Shōrin-ryū Kyudōkan
        <br/>
        Shorin-Ryu Reihokan
        <br/>
        Matsubayashi-ryū
        <br/>
        Shōbayashi Shōrin-ryū
        <br/>
        Jyoshinmon Shōrin-ryū
        <br/>
        Yoshudokai Shorin-ryu
        <br/>
        Shubukan Shōrin-ryu"
    fontawesome_icon_name                 : school

  - title                                 : What does this app?
    description                           : Provide you curated content around different Katas. You’ll be able to watch videos where a sensei executes a kata and some others where they are teaching or making corrections to their students.
    fontawesome_icon_name                 : mobile-alt

  - title                                 : Do I have to pay something?
    description                           : All the content is free and available on Youtube. This app is only organizing and curating the content.
    fontawesome_icon_name                 : film

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#c71d0e"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#c71d0e"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"

# Analytics
ga_tracking: G-T5HM7H3579
ga_tracking_anonymize_ip: true










####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
